# Granularity data.

# Granularity ID definition.
int32 GRAN_S5=105   # 5 seconds
int32 GRAN_S10=110  # 10 seconds
int32 GRAN_S15=115  # 15 seconds
int32 GRAN_S30=130  # 30 seconds
int32 GRAN_M1=201   # 1 minute
int32 GRAN_M2=202   # 2 minutes
int32 GRAN_M3=203   # 3 minutes
int32 GRAN_M4=204   # 4 minutes
int32 GRAN_M5=205   # 5 minutes
int32 GRAN_M10=310  # 10 minutes
int32 GRAN_M15=315  # 15 minutes
int32 GRAN_M30=330  # 30 minutes
int32 GRAN_H1=401   # 1 hour
int32 GRAN_H2=402   # 2 hours
int32 GRAN_H3=403   # 3 hours
int32 GRAN_H4=404   # 4 hours
int32 GRAN_H6=406   # 6 hours
int32 GRAN_H8=408   # 8 hours
int32 GRAN_H12=412  # 12 hours
int32 GRAN_D=501    # 1 Day
int32 GRAN_W=601    # 1 Week

# Granularity ID.
int32 gran_id
