# oandapyV20.endpoints.accounts.AccountDetails(
# Reference:
#    https://oanda-api-v20.readthedocs.io/en/latest/endpoints/accounts/accountdetails.html

# ========================= Request =========================
# None

---
# ========================= Response =========================

# Result of this service process.
#   True:success
#   False:fail
bool result

# Fail reason code.
api_msgs/FailReasonCode frc_msg


# Client-provided margin rate override for the Account.
# The effective margin rate of the Account is the lesser of this value and
# the OANDA margin rate for the Account's division.
# This value is only provided if a margin rate override exists for the Account.
float32 margin_rate

# Current balance of the account.
int32 balance

# Number of Trades currently open in the Account. 
int32 open_trade_count

# Number of Positions currently open in the Account.
int32 open_position_count

# Number of Orders currently pending in the Account.
int32 pending_order_count

# Total profit/loss realized over the lifetime of the Account.
int32 pl

# Total realized profit/loss for the account since it was last reset by the client.
int32 resettable_pl

# Total amount of financing paid/collected over the lifetime of the account.
int32 financing

# Total unrealized profit/loss for all Trades currently open in the Account.
int32 unrealized_pl

# Net asset value of the Account.
# Equal to Account balance + unrealizedPL.
int32 nav

# Margin currently used for the Account.
int32 margin_used

# Margin available for Account currency.
int32 margin_available

# Value of the Account's open positions represented in the Account's home currency.
int32 position_value

# Account's margin closeout percentage[%].
# When this value is 100.0[%] or above the Account is in a margin closeout situation.
float32 margin_closeout_percent
