# oandapyV20.endpoints.instruments.InstrumentsCandles
# Reference:
#    https://oanda-api-v20.readthedocs.io/en/latest/endpoints/instruments/instrumentlist.html

# ========================= Request =========================
# The granularity.
api_msgs/Granularity gran_msg

# The Instrument.
api_msgs/Instrument inst_msg

# The start of the time range to fetch candlesticks for.
# String format is "%Y-%m-%dT%H:%M:00.000000000Z"
string dt_from

# The end of the time range to fetch candlesticks for.
# String format is "%Y-%m-%dT%H:%M:00.000000000Z"
string dt_to

---
# ========================= Response =========================

# The result of this service process.
#   True:success
#   False:fail
bool result

# The fail reason code.
api_msgs/FailReasonCode frc_msg

# The list of candle message.
api_msgs/Candle[] cndl_msg_list

# A flag indicating if the latest candlestick is complete.
bool is_latest_complete