# oandapyV20.endpoints.orders.OrderCreate
# Reference:
#    https://oanda-api-v20.readthedocs.io/en/latest/endpoints/orders/ordercreate.html

# Order type defintion
string TYP_MARKET="MARKET"
string TYP_LIMIT="LIMIT"
string TYP_STOP="STOP"

# Order instrument defintion
string INST_USD_JPY="USD_JPY"
string INST_EUR_JPY="EUR_JPY"
string INST_EUR_USD="EUR_USD"

# ========================= Request =========================
# The type of the order.
string type

# The "limit" or "stop" price.
float32 price

# Instrument to open the order on.
string instrument

# The number of units to open order for.
# If positive value is set, it is a "buy" direction,
# and if a negative value is set, it is a "sell" direction.
int32 units

# The take profit price.
float32 take_profit_price

# The stop loss price.
float32 stop_loss_price

---
# ========================= Response =========================
# The type of the order.
string type

# Instrument to open the order on.
string instrument

# The order fill time.
string time
