# oandapyV20.endpoints.trades.TradeDetails
# Reference:
#    https://oanda-api-v20.readthedocs.io/en/latest/endpoints/trades/tradedetails.html

# ========================= Request =========================
# Trade ID that was opened.
int32 trade_id

---
# ========================= Response =========================

# Result of this service process.
#   True:success
#   False:fail
bool result

# Fail reason code.
api_msgs/FailReasonCode frc_msg

# Contract price.
float32 contract_price

# Current state of the Trade.
api_msgs/TradeState trade_state_msg

# Number of units currently open for the Trade.
# This value is reduced to 0.0 as the Trade is closed.
int32 current_units

# Total profit/loss realized on the closed portion of the Trade.
float32 realized_pl

# Unrealized profit/loss on the open portion of the Trade.
float32 unrealized_pl

# Date/time when the Trade was opened.
string open_time

# TakeProfitOrder linked to an open Trade.
api_msgs/ProfitLossOrder profit_order_msg

# TakeProfitOrder linked to an open Trade.
api_msgs/ProfitLossOrder loss_order_msg
