# oandapyV20.endpoints.trades.TradeCRCDO
# Reference:
#    https://oanda-api-v20.readthedocs.io/en/latest/endpoints/trades/tradeCRCDO.html

# ========================= Request =========================
# The ID of the Trade that was opened.
int32 trade_id

# The take profit price.
float32 take_profit_price

# The stop loss price.
float32 stop_loss_price

---
# ========================= Response =========================

# The result of this service process.
#   True:success
#   False:fail
bool result

# The fail reason code.
api_msgs/FailReasonCode frc_msg

# The TakeProfitOrder linked to an open Trade.
api_msgs/ProfitLossOrderTransaction profit_order_transaction_msg

# The TakeProfitOrder linked to an open Trade.
api_msgs/ProfitLossOrderTransaction stop_loss_order_transaction_msg
