# oandapyV20.endpoints.trades.TradeClose
# Reference:
#    https://oanda-api-v20.readthedocs.io/en/latest/endpoints/trades/tradeclose.html

# ========================= Request =========================
# Trade ID that was opened.
int32 trade_id

---
# ========================= Response =========================

# Result of this service process.
#   True:success
#   False:fail
bool result

# Fail reason code.
api_msgs/FailReasonCode frc_msg

# Instrument to open the order on.
api_msgs/Instrument inst_msg

# Order fill time.
string time

# Number of units that the Trade was reduced by
int32 units

# Average price that the units were closed at.
# This price may be clamped for guaranteed Stop Loss Orders.
float32 price

# PL realized when reducing the Trade.
float32 realized_pl

# Half spread cost for the trade reduce/close.
# This can be a positive or negative value and is represented in the home currency of the Account.
float32 half_spread_cost
