# Cabdlestick(OHLC) data by datetime service.

# ========================= Request =========================
# Granularity message.
trade_manager_msgs/Granularity gran_msg

# Instrument message.
trade_manager_msgs/Instrument inst_msg

# Start of datetime to fetch candlesticks.
# The format is "%Y-%m-%dT%H:%M:%S".
# If want to set indefinite period, set blank as "".
string datetime_start

# End of datetime to fetch candlesticks for.
# The format is "%Y-%m-%dT%H:%M:%S".
# If want to set indefinite period, set blank as "".
string datetime_end

# Target dayofweeks.
# - Monday = 0
# - Tuesday = 1
# - Wednesday = 2
# - Thursday = 3
# - Friday = 4
# - Saturday = 5
# - Sunday = 6
int32[] dayofweeks

# Start of time range to fetch candlesticks.
# The format is "%H:%M:%S".
# If want to set indefinite period, set blank as "".
string time_from

# End of time range to fetch candlesticks.
# The format is "%H:%M:%S".
# If want to set indefinite period, set blank as "".
string time_to

---
# ========================= Response =========================

# List of candle message.
trade_manager_msgs/Candle[] cndl_msg_list

# Next update time.
# Format is "%Y-%m-%dT%H:%M:%S"
string next_update_time
