# Cabdlestick service for monitor.

# ========================= Request =========================
# The granularity.
trade_manager_msgs/Granularity gran_msg

# The Instrument.
trade_manager_msgs/Instrument inst_msg

# The start of the time range to fetch candlesticks for.
# The format is "%Y-%m-%dT%H:%M:00.000000000Z".
# If want to set indefinite period, set blank as "".
string dt_from

# The end of the time range to fetch candlesticks for.
# The format is "%Y-%m-%dT%H:%M:00.000000000Z".
# If want to set indefinite period, set blank as "".
string dt_to

---
# ========================= Response =========================

# The list of candle message.
trade_manager_msgs/CandleMnt[] cndl_msg_list
