# Order request service.

# ========================= Request =========================

# Instrument message.
trade_manager_msgs/Instrument inst_msg

# Order type message.
trade_manager_msgs/OrderType ordtyp_msg

# Order direction message.
trade_manager_msgs/OrderDir orddir_msg

# Quantity requested to be filled.
# The value must be "0" or positive.
# If a negative value is set, the request will be invalid.
# If "0" is set, be requested maximum order quantity in current account assets.
int32 units

# Entry price on selected "LIMIT" or "STOP" order.
# If the order type is "MARKET", this parameter is ignored.
float32 entry_price

# Entry expiration time on selected "LIMIT" or "STOP" order.
# Format is "%Y-%m-%dT%H:%M:%S".
# If the order type is "MARKET", this parameter is ignored.
# If is set an empty string(""), indefinite period.
string entry_exp_time

# Exit order price of take profit.
float32 take_profit_price

# Exit order price of stop loss.
float32 stop_loss_price

# Exit expiration time.
# Format is "%Y-%m-%dT%H:%M:%S".
# If is set an empty string(""), indefinite period.
string exit_exp_time

---
# ========================= Response =========================

# Requested ID.
int32 requested_id
