# Trade close request service.

# ========================= Request =========================

# Register ID to close trade.
int32 register_id

---
# ========================= Response =========================

# Result of service request.
#   True:success
#   False:fail
bool success
