# oandapyV20.endpoints.orders.OrderCancel
# Reference:
#    https://oanda-api-v20.readthedocs.io/en/latest/endpoints/orders/ordercancel.html

# ========================= Request =========================
# Order ID to perform the request on.
int32 order_id

---
# ========================= Response =========================

# Result of this service process.
#   True:success
#   False:fail
bool result

# Fail reason code.
api_server_msgs/FailReasonCode frc_msg
